services:
  db: 
    image: postgres:18.4
    ports: 
      - "5432:5432"
    container_name: filevault-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql
  backend:
    build:
      context: ./backend
    container_name: filevault-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on: 
      - db
  frontend:
    build:
      context: ./frontend
    container_name: filevault-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
volumes: 
  postgres_data:
